# Generated by Django 4.2.9 on 2024-02-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
