version: '3'


services:
    app:
        build: .
        command: python manage.py migrate && runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            db:
                condition: service_healthy

    db:
        restart: always
        image: postgres
        ports:
            - "5432:5432"

        env_file:
            -   .env

        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
