# Generated by Django 4.2.9 on 2024-02-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус подписки'),
        ),
    ]
