# Generated by Django 4.2.9 on 2024-03-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление'),
        ),
    ]
